<?php

// Implementation of hook_ctools_plugin_api().
function mn_searchlight_ctools_plugin_api($owner, $api) {
  if ($owner == 'feeds' && $api == 'plugins') {
    return array('version' => 1);
  }
}

// Implementation of hook_feeds_plugins
function mn_searchlight_feeds_plugins() {
  $path = drupal_get_path('module', 'mn_searchlight') .'/plugins';
  $info = array();
  $info['SearchlightDataProcessor'] = array(
    'name' => 'Searchlight Data processor',
    'description' => 'Create searchable data table records.',
    'help' => 'Create data table records from parsed content.',
    'handler' => array(
      'parent' => 'FeedsDataProcessor',
      'class' => 'SearchlightDataProcessor',
      'file' => 'SearchlightDataProcessor.inc',
      'path' => $path,
    ),
  );
  return $info;
}

function mn_searchlight_feeds_importer_default_alter($items) {
  $items['syndication']->config['processor']['plugin_key'] = 'SearchlightDataProcessor';
}
